<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="display-popup" style="display:none;"> 
	
    <div id="newsletter-popup">
		<div class="w-newsletter">
		<div class="row">
		<div class="col-lg-6 col-sm-6">
		<div class="newsletter-info">
			<div class="newsletter-content">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-popup-image')->toHtml(); ?>
				<div class="newsletter-description">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-popup-description')->toHtml(); ?>
				</div>
			</div>
		
       <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-popup-validate-detail">
           <!--
				 <div class="newsletter-image">
                   
                </div>
                <div class="newsletter-info">
                   

                    <div class="form-newsletter-popup">
                        <div class="input-box">
                            <input name="email" type="email" id="newsletter-popup-input" class="input-text"
                                   onfocus="if(this.value=='<?php echo __("Your email address") ?>') this.value='';"
                                   onblur="if(this.value=='') this.value='<?php echo __("Your email address") ?>';"
                                   value="<?php echo __("Your email address") ?>"
                                   data-validate="{required:true, 'validate-email':true}"/>
                        </div>

                        <div class="action-newsletter">
                            <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
                            echo __('Subscribe') ?>" type="submit">
										<span><?php /* @escapeNotVerified */
                                            echo __('Subscribe') ?></span>
                            </button>
                        </div>
                    </div>

                   
                </div>
				-->
				 <div class="subscribe-bottom">
                        <div id="uniform-dont-show-again" class="checker"><span><input id="dont-show-again"
                                                                                       type="checkbox"></span>
                        </div>
                        <label for="dont-show-again"><?php echo __('Don\'t show this popup again') ?></label>
                    </div>
        </form>
		</div>
    </div>
	<div class="col-lg-6 col-sm-6">
		 <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product-newsletter')->toHtml(); ?> 
	</div>
	</div>
	</div>
	</div>
</div>
