<?php
$_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="footer-style-1">
	<div class="container">
        <div class="footer-top">
			<div class="row no-gutters">
				<div class="col-xl-3 col-md-6">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-contact')->toHtml(); ?>
				</div>	
				<div class="col-xl-3 col-md-6">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-help')->toHtml(); ?>
				</div>	
				<div class="col-xl-3 col-md-6">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-userlink')->toHtml(); ?>
				</div>	
				<div class="col-xl-3 col-md-6">
					<div class="footer-block">
						<div class="footer-block-title"><?php echo __('Sign Up for Email');?></div>
						<div class="footer-block-content">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-1-newsletter')->toHtml(); ?>
							<div class="language-currency">
								<?php echo $this->getChildHtml("store_language"); ?>
								<?php echo $this->getChildHtml("currency"); ?>  
							</div>
						</div>
					</div>
					
				</div>	
			</div>
           
        </div>
	</div>
	<div class="container">
		<div class="footer-bottom">
            <div class="row align-items-center">    
                    <div class="col-md-6 payment-footer">
                        <?php if ($_config->getAdvanced('copyright_group/custom_copyright')) { ?>
                            <address><?php echo $_config->getAdvanced('copyright_group/copyright_content') ?></address>
                        <?php } else { ?>
                            <address><?php echo $this->getChildHtml("copyright"); ?></address>
                        <?php } ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer')->toHtml(); ?>
                    </div>
            </div>
        </div>
    </div>
</div>
 