/**
* Product 1
*/
.product-1-style .deals-countdown .deals-time .num-time{
	color: #<?php echo $themeColor; ?>;
}
.product-1-style .product-item-info .product-item-details .swatch-attribute.size .swatch-option.text:hover,
.product-1-style .product-item-info .product-item-details .swatch-attribute.size .swatch-option.text.selected {
	color: #<?php echo $themeColor; ?> !important;
}
/**
* Product 3
*/
.product-3-style .product-item-info .product-item-details .product-item-actions .actions-primary .action.tocart{
	background-color: #<?php echo $themeColor; ?>; 
}
.product-3-style  .product-item-info .product-item-details .product-item-name a:hover {
	color: #<?php echo $themeColor; ?> !important;
}
