/**
* Home page 1
*/

.block-detailproduct .block-filterproducts .block-content .product-item-info .product-item-details .product-item-inner .product-item-actions .action.primary:hover{
	background-color: #<?php echo $themeColor; ?>;
	border-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.newsletter-home .newsletter-content .action-button .action.primary:hover {
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.sm-popup-modal .actions-toolbar .primary button:hover {
	background-color: #<?php echo $themeColor; ?>;
}
.sm-popup-modal .trigger-create:hover {
	border-color: #<?php echo $themeColor; ?>;
}
.sm-popup-modal .open-popup-forgot:hover {
	color: #<?php echo $themeColor; ?>;
}

.hdt-collection-list-wrap .item .hdt-collection-bottom-content .hdt-collection-link:hover:after{
	background-color: #<?php echo $themeColor; ?>;
}
.home-page-1.title-style-home .btn-viewmore:hover {
	border-color: #<?php echo $themeColor; ?>;
	color:#<?php echo $themeColor; ?>;
}
/**
* Home page 3
*/
.hdt-section-dealtime .hdt-col-content a:hover:after{
	background-color: #<?php echo $themeColor; ?>; 
}
.hdt-collections-list-simple .hdt-collection-other_link a:hover{
	color: #<?php echo $themeColor; ?>; 
}
.hdt-collections-list-simple .hdt-collection-other_link a:hover:after{
	background-color: #<?php echo $themeColor; ?>; 
}
.block-testimonial-content > .container .hdt-testimonial-pr-title:hover {
	color: #<?php echo $themeColor; ?>; 
}
/**
* Home page 4
*/
.home-page-4 .sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn:hover{
	border: 1px solid #<?php echo $themeColor; ?>;
	color:#<?php echo $themeColor; ?>;
}
/**
* Home page 5
*/
.hdt-banner_masonry .hdt-banner_masonry__item .hdt-content_wrap .hdt-content .hdt-btn-link:hover{
	color:#<?php echo $themeColor; ?>;
}

/**
* Home page 6
*/
.home-page-6 .block-marquee{
	background: #<?php echo $themeColor; ?>;
}
.home-page-6 .hdt-banner_masonry__item .hdt-content_wrap .hdt-content .hdt-btn{
	border: 1px solid #<?php echo $themeColor; ?>;
    background-color: #<?php echo $themeColor; ?>;
}
.id6-block-dealtime{
	background-color: #<?php echo $themeColor; ?>;
}

/**
* Home page 7
*/
.home-page-7 .slidershow .slidershow-type-2 .owl-stage-outer .owl-item .item .caption-panel p.slide-text{
	color:#<?php echo $textColor ?>;
}
.home-page-7 .slidershow .slidershow-type-2 .owl-stage-outer .owl-item .item .caption-panel p.slide-subtitle{
	color:#<?php echo $textColor ?>;
}
.home-page-7.title-style-home .block-title{
	color:#<?php echo $textColor ?>;
}
.home-page-7.title-style-home .block-title strong{
	color:#<?php echo $textColor ?>;
}
.home-page-7 .block-deal7 .block-filterproducts .products-grid:not(.wishlist) .product-item-info .deals-countdown .deals-time .num-time{
	color:#<?php echo $textColor ?>;
}
.home-page-7 .block-deal7 .block-filterproducts .products-grid:not(.wishlist) .product-item-info .deals-countdown .deals-time .title-time{
	color:#<?php echo $textColor ?>;
}
.home-page-7 .block-deal7 .block-filterproducts .products-grid:not(.wishlist) .product-item-info .deal-progress-bar{
	background-color: #<?php echo $themeColor; ?>;
}
.home-page-7 .block-deal7 .block-filterproducts .products-grid:not(.wishlist) .product-item-info .product-item-details .price-box .price{
	color: #<?php echo $themeColor; ?>;
}
.home-page-7 .id7-block-listingtabs .sm-listing-tabs .ltabs-wrap .ltabs-tabs-container .ltabs-tabs li.tab-sel{
	border:2px solid #<?php echo $themeColor; ?>;
}
.home-page-7 .id7-block-listingtabs .sm-listing-tabs .ltabs-wrap .ltabs-tabs-container .ltabs-tabs li:hover{
	color: #<?php echo $themeColor; ?>;
}
/**
* Home page 10
*/
.id10-banner-sale .hdt-banner__item .hdt-item_inner .hdt-content_wrap{
	background-color: #<?php echo $themeColor; ?>;
}
.block-deal10 .block-filterproducts .block-title strong{
	color: #<?php echo $themeColor; ?>;
}
.block-deal10 .block-filterproducts{
	border:1px solid #<?php echo $themeColor; ?>;
}
.home-page-10 .hdt-banner_masonry .hdt-banner_masonry__item .hdt-content_wrap .hdt-content .hdt-btn{
	background-color: #<?php echo $themeColor; ?>;
	border:1px solid #<?php echo $themeColor; ?>;
}
.home-page-10 .block-categories .cat-wrap .item .image-cat{
	border:2px solid #<?php echo $themeColor; ?>;
}
.id10-product-slider .block-filterproducts .products-grid:not(.wishlist) .product-item-info .product-item-details .product-item-actions .actions-primary .action{
	background: #<?php echo $themeColor; ?>;
}
.block-deal10 .block-filterproducts .products-grid:not(.wishlist) .product-item-info .deal-progress-bar{
	background-color: #<?php echo $themeColor; ?>;
}