/**
* Footer 1
*/

.footer-block .links-footer li a:hover{
	color: #<?php echo $themeColor; ?> !important;
}
.ft-socials-list li a:hover {
	color: #<?php echo $themeColor; ?> !important;
	border-color:#<?php echo $themeColor; ?> !important;
	fill:#<?php echo $themeColor; ?> !important;
}
.footer-button .ft-direction:hover{
	color: #<?php echo $themeColor; ?> !important;
	
}
.footer-button .ft-direction:hover:after{
	background-color:#<?php echo $themeColor; ?>;
}
/**
* Footer 5
*/
.footer-5-style .right-header-top .language-currency .heading-switcher{
	color:#<?php echo $linkColor; ?>;
}
.footer-5-style .right-header-top .language-currency .heading-switcher:hover{
	color:#<?php echo $themeColor; ?>;
}
.footer-5-style .newsletter-content .action-button button{
	background:#<?php echo $linkColor; ?>;
}
.footer-5-style .ft-socials-list li a{
	border:1px solid #<?php echo $linkColor; ?>;
}

/**
* Footer 6
*/
.footer-6-style .right-header-top .language-currency .heading-switcher{
	color:#<?php echo $linkColor; ?>;
}
.footer-6-style .right-header-top .language-currency .heading-switcher:hover{
	color:#<?php echo $themeColor; ?>;
}
.footer-6-style .newsletter-content .action-button button{
	background:#<?php echo $linkColor; ?>;
}
.footer-6-style .ft-socials-list li a{
	border:1px solid #<?php echo $linkColor; ?>;
}