/**
* Header 1
*/
.header-container > .container .close-search:hover {
	color: #<?php echo $themeColor; ?>;
}
.header-1-style .header-top{
	color: #<?php echo $textOnThemeColor; ?>;
	background-color: #<?php echo $themeColor; ?>;
}
.header-1-style .customer-actions .setting-block:hover:before{
	color: #<?php echo $themeColor; ?>;
}
.block-minicart .amount .price-wrapper:first-child .price{
	color: #<?php echo $themeColor; ?>;
}
.header-1-style .desktop-menu .horizontal-block .sm_megamenu_menu > li > a:before{
background-color: #<?php echo $themeColor; ?>;
}

.header-1-style .header-bottom .horizontal-block .sm_megamenu_menu > li:hover > a,
.header-1-style .header-bottom .horizontal-block .sm_megamenu_menu > li.sm_megamenu_actived > a{
	color: #<?php echo $themeColor; ?>;
}
.header-1-style .search-container .block-search .actions button:hover{
	color: #<?php echo $themeColor; ?>;
}
.header-1-style .header.links .customer-welcome .customer-menu .header.links li.authorization-link a:hover{
	background-color: #<?php echo $themeColor; ?>;
	border-color: #<?php echo $themeColor; ?>;
}
.cms-index-index.header-1-style .header-bottom .horizontal-block .sm_megamenu_menu > li.home-item > a{
	color: #<?php echo $themeColor; ?>;
}
.header-container .minicart-wrapper .action.showcart .counter.qty{
	color: #<?php echo $textOnThemeColor; ?>;
	background-color: #<?php echo $themeColor; ?>;
}
.header-wishlist a .count,
.header-content .customer-actions .search-container a.icon-search1:hover,
.header-content .customer-actions .customer-links .open-popup-login:hover,
.header-wishlist a:hover:after,
.header-container .minicart-wrapper .action.showcart:hover:after{
	background-color: #<?php echo $themeColor; ?> !important;
}

.slider-header-text a{
	color: #<?php echo $themeColor; ?>;
	border-color: #<?php echo $themeColor; ?>;
}

/**
* Index 5
*/
.header-5-style .header-top .block-marquee{
	background-color: #<?php echo $themeColor; ?>;
}
.header-5-style .header-top .topbar-close .btn-close{
	background-color: #<?php echo $themeColor; ?>;
}
/**
* Index 6
*/
.header-6-style .header-compare li a:hover{
	background-color: #<?php echo $themeColor; ?>;
}
/**
* Index 7
*/
.header-7-style .right-header-top .language-currency .heading-switcher{
	color:#<?php echo $linkColor; ?>;
}
.header-7-style .right-header-top .language-currency .heading-switcher:hover{
	color:#<?php echo $themeColor; ?>;
}
/*
.header-7-style .header-content .search-container .block-search .actions .action.search{
	background-color:#<?php echo $linkColor; ?>;
}
*/
.header-7-style .header-content .search-container .block-search .actions .action.search:hover{
	background-color: #<?php echo $themeColor; ?>;
}
.header-7-style .header-content .customer-actions .customer-links .open-popup-login:before{
	background-color:#<?php echo $linkColor; ?>;
}
.header-7-style .header-content .customer-actions .customer-links .open-popup-login:hover:before{
	background-color: #<?php echo $themeColor; ?>;
}
.header-7-style .header-compare li a{
	color:#<?php echo $linkColor; ?>;
}
.header-7-style .header-compare li a:hover{
	color:#<?php echo $linkHoverColor; ?>;
}
.header-7-style .header-compare li a:before{
	background-color:#<?php echo $linkColor; ?>;
}
.header-7-style .header-compare li a:hover:before{
	background-color:#<?php echo $themeColor; ?>;
}
.header-7-style .header-container .minicart-wrapper .action.showcart:after{
	background-color:#<?php echo $linkColor; ?>;
}
.header-7-style .header-container .minicart-wrapper .action.showcart:hover:after{
	background-color:#<?php echo $themeColor; ?>;
}

.header-7-style .vertical-menu-block .block-title-menu{
	background-color:#<?php echo $themeColor; ?>;
}
.header-7-style .header-hotline .hdt-number a{
	color:#<?php echo $linkHoverColor; ?>;
}

@media (min-width: 769px), print {
    .vertical-menu-block .navigation .level0 > .level-top:hover, .navigation .level0 > .level-top.ui-state-focus {
        color: #<?php echo $linkHoverColor; ?>;
    }
}

/**
* Index 9
*/
.header-9-style .ontop-element.menu-on-top .horizontal-block .horizontal-menu .horizontal-megamenu-block .sm_megamenu_menu > li > a:hover{
	color: #<?php echo $themeColor; ?>;
}
.header-9-style .ontop-element.menu-on-top .header-content .customer-actions .search-container a.icon-search1:hover,
.header-9-style .ontop-element.menu-on-top .header-content .customer-actions .customer-links .open-popup-login:hover,
.header-9-style .ontop-element.menu-on-top .header-wishlist a:hover:after,
.header-9-style .ontop-element.menu-on-top .minicart-wrapper .action.showcart:hover:after{
	background: #<?php echo $themeColor; ?>;
}

/**
* Index 10
*/
.header-10-style .right-header-top .language-currency .heading-switcher{
	color:#<?php echo $linkColor; ?>;
}
.header-10-style .right-header-top .language-currency .heading-switcher:hover{
	color:#<?php echo $themeColor; ?>;
}
/*
.header-10-style .header-content .search-container .block-search .actions .action.search{
	background-color:#<?php echo $linkColor; ?>;
}
*/
.header-10-style .header-content .search-container .block-search .actions .action.search:hover{
	background-color: #<?php echo $themeColor; ?>;
}
.header-10-style .header-content .customer-actions .customer-links .open-popup-login:before{
	background-color:#<?php echo $linkColor; ?>;
}
.header-10-style .header-content .customer-actions .customer-links .open-popup-login:hover:before{
	background-color: #<?php echo $themeColor; ?>;
}
.header-10-style .header-compare li a{
	color:#<?php echo $linkColor; ?>;
}
.header-10-style .header-compare li a:hover{
	color:#<?php echo $linkHoverColor; ?>;
}
.header-10-style .header-compare li a:before{
	background-color:#<?php echo $linkColor; ?>;
}
.header-10-style .header-compare li a:hover:before{
	background-color:#<?php echo $themeColor; ?>;
}
.header-10-style .header-container .minicart-wrapper .action.showcart:after{
	background-color:#<?php echo $linkColor; ?>;
}
.header-10-style .header-container .minicart-wrapper .action.showcart:hover:after{
	background-color:#<?php echo $themeColor; ?>;
}

.header-10-style .vertical-menu-block .block-title-menu{
	background-color:#<?php echo $themeColor; ?>;
}
.header-10-style .header-hotline .hdt-number a{
	color:#<?php echo $linkHoverColor; ?>;
}
