/**
* $themeColor, $themeColorDarken, $textColor, $textOnThemeColor, $linkColor, $linkHoverColor, $linkOnThemeColor, $linkHoverOnThemeColor
*/

/**
* THEME HEADER COLOR
*/
<?php include($block->getTemplateFile("Sm_Themecore::themecore/css/theme-header.phtml")); ?>


/**
* THEME HOME
*/
<?php include($block->getTemplateFile("Sm_Themecore::themecore/css/theme-home.phtml")); ?>

/**
* THEME FOOTER
*/
<?php include($block->getTemplateFile("Sm_Themecore::themecore/css/theme-footer.phtml")); ?>

/**
* THEME PRODUCT
*/
<?php include($block->getTemplateFile("Sm_Themecore::themecore/css/theme-product.phtml")); ?>

.action-close:hover, .table-comparison .cell.remove > a:hover:before {
	color: #<?php echo $themeColor; ?>;
}

/**
* Header mobile
*/

.header-mobile .mobile-top{
background-color: #<?php echo $themeColor; ?>;
}
.minicart-mobile .minicart-wrapper .action.showcart .counter.qty{ 
	background-color: #<?php echo $themeColor; ?> !important;
	color: #<?php echo $textOnThemeColor; ?> !important; 
	
}

.header-mobile .mobile-bottom .block-search-mobile .form.minisearch .actions button:hover,
.header-mobile .mobile-bottom .block-search-mobile .form.minisearch .actions button:focus {
	color: #<?php echo $themeColor; ?>;
}
.minicart-wrapper .block-minicart .btn-checkout-cart .action.viewcart:hover{
	border-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $themeColor; ?>;
}
.header-container .close-search:hover:after{
	color: #<?php echo $themeColor; ?> !important;
}
.modal-custom .action-close:hover:before, 
.modal-popup .action-close:hover:before, 
.modal-slide .action-close:hover:before{
	color: #<?php echo $themeColor; ?> !important;
}
/**
* Mobile layout
*/


.myaccount-dropdown .content-dropdown .block-customer-login .actions-toolbar .primary .action{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.mb-header-device .minicart-wrapper .action.showcart .counter.qty{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.mb-header-device .block-minicart .block-content > .actions > .primary .action.primary{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-mobile .footer-top{
background-color: #<?php echo $themeColor; ?>;
}

.footer-mobile .support-mobile ul li a{
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-mobile .support-mobile ul li a:before {
color: #<?php echo $themeColor; ?>;
}
.show-minicart-drop body.action-click-dropcart .header-container .minicart-wrapper .mage-dropdown-dialog .block-minicart #minicart-content-wrapper #slider_minicart .product-type-list .product-item .quickview-handler:hover {
	background-color: #<?php echo $themeColor; ?>;
}
#newsletter-popup .newsletter-info .newsletter-content .newsletter-description .hdt-btn{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}
#newsletter-popup .newsletter-info .newsletter-content .newsletter-description .hdt-btn:hover{
	background-color: #<?php echo $themeColorDarken; ?>;
}
.mobile-newsletter .action-button button:active,
.mobile-newsletter .action-button button:focus,
.mobile-newsletter .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.footer-mobile .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* General
*/

.mega-feature-content .feature-layout .ft-item:hover{
border-color: #<?php echo $themeColor; ?>;
}
.price-box .special-price .price,
.price-box .price-from > .price-container .price,
.price-box .price-to > .price-container .price{
	color: #<?php echo $themeColor; ?> !important;  
}
.fieldset-bundle-options .field.option > .label:before{
	background-color: #<?php echo $themeColor; ?> !important;  
	
}

.text-theme-color{
color: #<?php echo $themeColor; ?>;
}

.social-popup ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.bundle-actions .action.primary:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.mega-feature-content ul li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.extend-container .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel{
color: #<?php echo $themeColor; ?>;
}

.extend-container .sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel:before{
background-color: #<?php echo $themeColor; ?>;
}

.extend-container .sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.extend-container .sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.extend-container .deals-countdown .deals-time .num-time{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}



/**
* Listing
*/

.sidebar .block.filter .filter-options .filter-options-content ol li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}
.sidebar .block.filter .filter-options .filter-options-content ol li a:hover:before{
background-color: #<?php echo $themeColor; ?>;
}
#price-slider .ui-slider-handle,#price-slider .ui-slider-range{
	background-color: #<?php echo $themeColor; ?>;
}

/**
* Detail page
*/
.product-info-main .modal-dialog .modal-content .modal-header .close:hover {
	color: #<?php echo $themeColor; ?> !important;
}
.qty-control .qty-btn:hover{
background-color: #<?php echo $themeColor; ?>;
}

.qty-control .qty-btn:hover:after,
.qty-control .qty-btn:hover:before{
background-color: #<?php echo $textOnThemeColor; ?>;
}

.fotorama__active .fotorama__dot{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
}



.gallery-placeholder .fotorama__thumb__arr:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}
.product-info-main .box-tocart .actions .action.primary.tocart:hover, 
.product-options-bottom .box-tocart .actions .action.primary.tocart:hover{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>!important;
}



.product-info-main .box-tocart .field.qty .control-qty .quantity-controls:hover{
color: #<?php echo $themeColor; ?>;
}
.product-info-main .product-reviews-summary .reviews-actions a:hover{
	color: #<?php echo $themeColor; ?>;
}
.review-form .action.submit.primary:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>!important;
}

.review-form .action.submit.primary:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-info-main .product-social-links .action:hover, 
.product-info-main .product-addto-links .action:hover{ 
	color: #<?php echo $themeColor; ?> !important;
}
.action.primary.buynow{
	background-color: #<?php echo $themeColor; ?> !important;
}
.action.primary.buynow:hover{
	background-color: #<?php echo $themeColorDarken; ?> !important;
}
.countdown-time-detail{
	border-color: #<?php echo $themeColor; ?>;
}
.countdown-time-detail .countdown-static{
	color: #<?php echo $themeColor; ?>;
}
.product-info-main .product-extra-link .hdt-inline-flex:hover .hdt-product__extra-text,
.product-info-main .product-extra-link .hdt-inline-flex:hover .hdt-product-extra-icon svg{
	color: #<?php echo $themeColor; ?>;
}
.sticky-product-action .sticky-qty .qty-control .qty-btn.qty-plus:hover:before,
.sticky-product-action .sticky-qty .qty-control .qty-btn.qty-minus:hover:before,
.product-info-main .box-tocart .fieldset .field.qty .control-qty .quantity-controls.quantity-minus:hover:before,
.product-info-main .box-tocart .fieldset .field.qty .control-qty .quantity-controls.quantity-plus:hover:before{
	background-color: #<?php echo $themeColor; ?>;
}
/**
* About Us
*/
.about-container .our-client-say .item .client-say{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.about-container .our-client-say .item .client-say:after{
	border-left-color: #<?php echo $themeColor; ?>;
}
.bonus-title:before{
	background-color: #<?php echo $themeColor; ?>;
}
.about-container .our-member .bonus-content .item:hover .content h3{
	color: #<?php echo $themeColor; ?>;
}
.cms-faqs .hdt-other-content .contact-link-1:hover:after,
.cms-faqs .hdt-other-content .contact-link:hover {
	background-color: #<?php echo $themeColor; ?>;
}

.list-why-choose li:before{
color: #<?php echo $themeColor; ?>;
}

/**
* Contact Us
*/

.contact-us-info .info-contact li:before{
	color: #<?php echo $themeColor; ?>;
}

.block-contact-form .actions-toolbar .primary button:hover{
	background: #<?php echo $themeColor; ?>;
}
/**
* Newsletter popup
*/

.form-newsletter-popup .action-newsletter button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}
.w-newsletter .subscribe-bottom input[type="checkbox"]:checked{
	background-color: #<?php echo $themeColor; ?>;
}

/**
* Blog page
*/

.post-content.post-custom .post-description .post-title a:hover{
color: #<?php echo $linkHoverColor; ?>;
}
/**
* fancybox
*/

.fancybox-close:hover:before {
	color: #<?php echo $themeColor; ?>;
}
.customer-account-create .form-create-account .actions-toolbar .primary button:hover,
.customer-account-login .login-container .actions-toolbar .primary button:hover,
.customer-account-login .login-container .actions-toolbar .create.primary:hover{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.breadcrumbs a:hover {
	color: #<?php echo $themeColor; ?> !important;
}
.sm-notfound a.back-home:hover{
	background-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $textOnThemeColor; ?>;
}
.widget.block-tagclaud .tagclaud-hld .largest:hover, 
.widget.block-tagclaud .tagclaud-hld .medium:hover, 
.widget.block-tagclaud .tagclaud-hld .smallest:hover{
	border-color: #<?php echo $themeColor; ?>;
}
.cms-our-store .our-store-content .hdt-btn:hover {
	border-color: #<?php echo $themeColor; ?>;
	color: #<?php echo $themeColor; ?>;
}
.bg-grey.product-top-home .block-list-products .hdt-tetimonials-item .hdt-tetimonials-inner .product-reviews-summary .rating-summary .rating-result > span:before{
	color: #<?php echo $themeColor; ?> !important;
}