<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */
              echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */
            echo __('* Required Fields') ?>">
                <div class="field email required">
                    <div class="control">
                        <input placeholder="<?php echo __('User name or email address') ?>" name="login[username]"
                               value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
                               id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */
                        echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input placeholder="<?php echo __('Password') ?>" name="login[password]"
                               type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass" title="<?php /* @escapeNotVerified */
                        echo __('Password') ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
				 <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ 
                        echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */
                                echo __('Forgot Your Password?') ?></span></a></div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2">
                            <span><?php /* @escapeNotVerified */
                                echo __('Sign In') ?></span></button>
                       
                        <a class="create-account-button"
                           href="<?php echo $this->getUrl('customer/account/create') ?>"><?php echo __('New customer? Create your account ') ?></a>
                    </div>
                   
                </div>
            </fieldset>
        </form>
    </div>
</div>
