<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */

$_config     = $this->helper('Sm\Ecomus\Helper\Data');
$_configCore = $this->helper('Sm\Themecore\Helper\Data');
$mediaSrc    = $_config->getMediaUrl();
$logoMobile  = $_configCore->getGeneral('mobile_layout/logo_mobile');
$menuType    = $_configCore->getGeneral('navigation_group/menu_style');
$breakPoint  = $_configCore->getGeneral('mobile_layout/mobile_break_point');
?>

<div class="header-mobile ontop-element header-container" id="sm-header-mobile" data-menutype="<?php echo $menuType; ?>"
     data-breakpoint="<?php echo $breakPoint; ?>">
	<div class="sticky-top"> 
	<div class="container">
		<div class="content-group-block align-items-center">
			<div class="group-block"> 
               <div class="header-mobile">
					 <?php echo $this->getChildHtml("nav.mobile"); ?>
			   </div>
			  
				<div class="mobile-logo">
                    <a href="<?php echo $this->getUrl('') ?>">
                        <img src="<?php echo $mediaSrc . 'logomobile/' . $logoMobile; ?>"
                             alt="<?php /* @escapeNotVerified */
                             echo $block->getLogoAlt() ?>"
                             width="<?php echo $_configCore->getGeneral('mobile_layout/logomobile_width'); ?>"
                             height="<?php echo $_configCore->getGeneral('mobile_layout/logomobile_height'); ?>"/>
                    </a>
                </div>
				<div class="header-right d-flex align-items-center"> 
				<div id="mysearchtop-drop" class="mysearchtop-drop">
					<a class="button-sticky" href="javascript:void(0)">  
						<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="currentColor">
							<path d="M17.7241 16.1932L13.6436 12.1127C14.626 10.8049 15.1563 9.21299 15.1546 7.57728C15.1546 3.39919 11.7554 0 7.57728 0C3.39919 0 0 3.39919 0 7.57728C0 11.7554 3.39919 15.1546 7.57728 15.1546C9.21299 15.1563 10.8049 14.626 12.1127 13.6436L16.1932 17.7241C16.3998 17.9088 16.6692 18.0073 16.9461 17.9996C17.2231 17.9918 17.4865 17.8783 17.6824 17.6824C17.8783 17.4865 17.9918 17.2231 17.9996 16.9461C18.0073 16.6692 17.9088 16.3998 17.7241 16.1932ZM2.16494 7.57728C2.16494 6.50682 2.48237 5.4604 3.07708 4.57034C3.6718 3.68029 4.51709 2.98657 5.50607 2.57693C6.49504 2.16728 7.58328 2.0601 8.63318 2.26893C9.68307 2.47777 10.6475 2.99325 11.4044 3.75018C12.1613 4.5071 12.6768 5.47149 12.8856 6.52138C13.0945 7.57128 12.9873 8.65952 12.5776 9.64849C12.168 10.6375 11.4743 11.4828 10.5842 12.0775C9.69416 12.6722 8.64774 12.9896 7.57728 12.9896C6.14237 12.9879 4.76672 12.4171 3.75208 11.4025C2.73744 10.3878 2.16666 9.01219 2.16494 7.57728Z"></path>
						  </svg>
					</a>
					
				</div>
				<div class="mobile-cart"> 
					 <div id="minicart-mobile" class="minicart-mobile"><span
											class="hidden"><?php echo __('Cart Mobile'); ?></span></div>
				</div>
				
				</div>
			</div>
		</div>
	</div>
</div> 
</div>