<?php
/*------------------------------------------------------------------------
# SM Categories - Version 3.2.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getList();
?>

<div class="list-categories">
    <div class="container">
        <?php if (!empty($list)) {
            $_config           = $this->helper('Sm\Themecore\Helper\Data');
            $enableLadyLoading = $_config->getAdvanced('lazyload_group/enable_ladyloading');
            $mediaSrc          = $_config->getMediaUrl();

            if ($enableLadyLoading) {
                $imgClass = 'lazyload';
            } else {
                $imgClass = '';
            }
            ?>
            <div class="cat-wrap row">
                <?php foreach ($list as $item) { ?>
                    <div class="item col-lg-4 col-md-4 col-sm-4 col-6">
                        <div class="content-box">
                            <?php if ($item['cat_image']) { ?>
                                <div class="image-cat">
                                    <a href="<?php echo $item['url'] ?>" title="<?php echo $item['name'] ?>">
                                        <img class="<?php echo $imgClass; ?>"
                                            <?php if ($enableLadyLoading) { ?>
                                                src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                data-src="<?php echo $item['cat_image']; ?>"
                                                width="1" height="1"
                                            <?php } else { ?>
                                                src="<?php echo $item['cat_image']; ?>"
                                            <?php } ?>
                                             alt="<?php echo $item['name'] ?>"/>
                                    </a>
                                </div>
                            <?php } ?>

                            <div class="child-cat">
                                <div class="cat-title">
                                    <a href="<?php echo $item['url'] ?>" title="<?php echo __($item['name']) ?>">
                                       <span> <?php echo $item['name']; ?></span>
										<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10" fill="none"><path d="M1.07692 10L0 8.92308L7.38462 1.53846H0.769231V0H10V9.23077H8.46154V2.61538L1.07692 10Z" fill="currentColor"></path></svg>
                                    </a>
                                </div> 
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        <?php } else { ?>
            <div class="message info empty">
                <div><?php /* @escapeNotVerified */
                    echo __('We can\'t find categories matching the selection.') ?></div>
            </div>
        <?php } ?>
    </div>
</div>


