<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/**
 * Enable lazy loading for images with borders and if variable enable_lazy_loading_for_images_without_borders
 * is enabled in view.xml. Otherwise small size images without borders may be distorted. So max-width is used for them
 * to prevent stretching and lazy loading does not work.
 */
$borders                         = (bool)$block->getVar('product_image_white_borders', 'Magento_Catalog');
$enableLazyLoadingWithoutBorders = (bool)$block->getVar(
    'enable_lazy_loading_for_images_without_borders',
    'Magento_Catalog'
);
$width = (int)$block->getWidth();
$height = (int)$block->getHeight();
$paddingBottom                   = $block->getRatio() * 100;
$_config                         = $this->helper('Sm\Themecore\Helper\Data');
$imageHelper                     = $this->helper('Sm\Themecore\Helper\Image');
$enableLadyLoading               = $_config->getAdvanced('lazyload_group/enable_ladyloading');
$enableHoverImage                = $_config->getAdvanced('product_group/show_imagehover');
$mediaSrc                        = $_config->getMediaUrl();
$imageDisplayArea                = 'category_page_grid_hover';
$imageDefault                    = $escaper->escapeUrl($block->getImageUrl());
$imageHover                      = $imageHelper->getItemImage($block->getProductId(), $imageDisplayArea);
$tag_id = "products-" . rand();
if (strpos($imageHover, '/product/placeholder/')) {
    $checkHoverImage = false;
} else {
    $checkHoverImage = true;
}

if ($enableLadyLoading) {
    $imgClass = 'lazyload';
} else {
    $imgClass = '';
}
?>
<span class="<?php echo $tag_id ;?> product-image-container product-image-container-<?= /* @noEscape */
$block->getProductId() ?>" style="width: <?php echo $width . "px"; ?>">
    <span class="product-image-wrapper">
        <img class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?> <?php echo $imgClass; ?>"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
            <?php endforeach; ?>

        <?php if ($enableLadyLoading) { ?>
            src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
            data-src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
        <?php } else { ?>
            src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
        <?php } ?>

            loading="lazy"
            <?php if ($borders || $enableLazyLoadingWithoutBorders): ?>
                width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
                height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
            <?php else: ?>
                max-width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
                max-height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
            <?php endif; ?>
            alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"/>

        <?php if ($imageHover !== $imageDefault && $enableHoverImage && $checkHoverImage) { ?>
            <img class="image-product-hover <?php echo $imgClass; ?>"
                 <?php if ($enableLadyLoading) { ?>
                     src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                     data-src="<?= $imageHover ?>"
                 <?php } else { ?>
                     src="<?= $imageHover ?>"
                 <?php } ?>
                <?php if ($borders || $enableLazyLoadingWithoutBorders): ?>
                    width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
                    height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
                <?php else: ?>
                    max-width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
                    max-height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
                <?php endif; ?>
                 alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
            />
        <?php } ?>

    </span>
</span>
<?php
$styles = <<<STYLE
.{$tag_id}.product-image-container-{$block->getProductId()} {
    width: {$width}px;
    height: auto;
    aspect-ratio: {$width} / {$height};
}
.product-image-container-{$block->getProductId()} span.product-image-wrapper {
    height: 100%;
    width: 100%;
}
@supports not (aspect-ratio: auto) { 
    .product-image-container-{$block->getProductId()} span.product-image-wrapper {
        padding-bottom: {$paddingBottom}%;
    }
}
STYLE;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], $styles, false) ?>
