<?php
/**
 *
 * SM Listing Tabs - Version 2.7.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */
 
use Magento\Framework\App\Action\Action;

$_productCollection = $this->_ajaxLoad();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Themecore\Helper\Data');

$viewMode        = 'grid';
$image           = 'category_page_grid';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$showWishlist    = true;
$showCompare     = true;
$showCart        = true;
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = 0;
if ($block->getPositioned()) {
    $pos    = $block->getPositioned();
}

if (count($_productCollection)){
    /**
     * Position for actions regarding image size changing in vde if needed
     */

    ?>
    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
    <?php foreach ($_productCollection as $_product):
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();		
        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
        $cat       = $product->getCategoryCollection()->addAttributeToSelect('*');

        ?>
        
            <div class="item product product-item">
            <div class="product-item-info" data-container="product-grid">
                <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;"';
                }
                ?>
                
                <?php // Product Image ?>
                    <div class="image-product">
                            <a href="<?php /* @escapeNotVerified */
                            echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>

                            <?= $_config->getLabelProduct($_product); ?>
                        </div>
                
                <div class="product details product-item-details box-info ">
                    
                    <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    ?>
                    <h2 class="product name product-item-name product-name">
                        <a class="product-item-link"
                            href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                        </a>
                    </h2>
                    <?php //echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                    <?php echo $block->getProductDetailsHtml($_product); ?>
                    
                        <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                        data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                        action="<?= /* @NoEscape */
                                                        $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product"
                                                            value="<?= /* @escapeNotVerified */
                                                            $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */
                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                            value="<?= /* @escapeNotVerified */
                                                            $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                            <span><?= /* @escapeNotVerified */
                                                __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */
                                                            __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                            __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                    data-post='<?php /* @escapeNotVerified */
                                                    echo $block->getAddToWishlistParams($_product); ?>'
                                                    class="action towishlist" data-action="add-to-wishlist"
                                                    title="<?php /* @escapeNotVerified */
                                                    echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare"
                                                    data-post='<?php /* @escapeNotVerified */
                                                    echo $compareHelper->getPostDataParams($_product); ?>'
                                                    title="<?php /* @escapeNotVerified */
                                                    echo __('Add to Compare') ?>">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                </div>
                
                
            </div>
        </div>
    <?php endforeach; ?>

<?php 
} else { ?>

		 <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>

<?php } ?>
