<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.3.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$count_item         = $_productCollection->count();
$nb_rows            = $this->_getConfig('row_items');
if (!$nb_rows) {
    $nb_rows = 1;
}
?>
<?php if (!$count_item): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode        = 'grid';
    $image           = 'category_page_list_small';
    $showDescription = false;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showWishlist    = true;
    $showCompare     = true;
    $showCart        = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = 0;
if ($block->getPositioned()) {
    $pos = $block->getPositioned();
};
    $tag_id = "filter-products-" . rand();
    ?>
    <div class="block block-list-products">
        <?php if (!empty($this->_getConfig('title_module'))) { ?>
            <div class="block-title">
                 <strong><?php echo __($this->_getConfig('title_module')); ?></strong>
				 <?php if (!empty($this->_getConfig('prev_text'))) { ?>
					<?php echo $this->_getConfig('prev_text'); ?>
				<?php } ?>
            </div>
        <?php } ?>

        <div class="block-content">
            <div id="<?php echo $tag_id; ?>" class="product-type-list">

                <?php
                if ($this->_getConfig('product_source') == 'countdown_products') {
                    $dateTo = $this->_getConfig('date_to', '');
                    ?>
                    <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
                        <div class="deals-time time-day">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-hours">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-mins">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-secs">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                    </div>
                <?php } ?>

                <?php $iterator = 1; ?>
                <div class="owl-carousel owl-theme products list items product-items">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php
                    $count = 0;
                    foreach ($_productCollection as $_product):
						$pro_id = $_product->getId();
                        $count++;
						$reviews = $block->getReviewCollection($pro_id);
						if(empty($reviews)) break;
                        ?>
                        <?php if (($count % $nb_rows == 1 || $nb_rows == 1)) { ?>
                        <div class="item-row">
                    <?php } ?>
                        <div class="hdt-tetimonials-item">
                            <div class="hdt-tetimonials-inner">
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>

                                <?php // Product Image
                                ?>
								 <div class="hdt-testimonial-info">
                                    
                                    <?php
                                        
                                        $productobj = $block->getProductById($pro_id);
                                        echo $block->getReviewsSummaryHtml($productobj, $templateType); 
                                    
                                       
                                    ?>
                                    <?php if(!empty($reviews)):
										//var_dump($reviews); die;
									?>
										
									<div class="hdt-testimonial-heading-item">
										<span class="hdt-testi-head hdt-s-text hdt-text-xl hdt-font-bold">
										   <?php echo $reviews[0]['title'];?>
										</span>
									</div>	
                                    <div class="hdt-testimonial-content hdt-s-text hdt-rte">
										  <p><?php echo '"'.$reviews[0]['detail'].'"';?></p>
									</div>   
                                    <div class="hdt-testimonial-author">
										<p class="hdt-testimonial-name hdt-text-base hdt-font-bold hdt-s-text">
											<?php echo $reviews[0]['nickname'];?>
										</p>
										<p class="hdt-testimonial-metas hdt-text-base hdt-s-text2">
											<?php echo __('Customer from France');?>
										</p>
									</div>    
                                    <?php endif;?>
                                    
                                </div>
								
								<div class="hdt-testimonial-product">
									<div class="image-product">
										<a href="<?php /* @escapeNotVerified */
										echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
										   tabindex="-1">
											<?php echo $productImage->toHtml(); ?>
										</a>
									</div>
									<div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
									<?php
                                    /* @escapeNotVerified */ 
                                    echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
									</div>
									<a href="<?php /* @escapeNotVerified */
										echo $_product->getProductUrl() ?>" class="pr-btn-link hdt-right-0 hdt-inline-flex hdt-justify-center hdt-align-center hdt-relative">
									 <svg xmlns="http://www.w3.org/2000/svg" width="9" height="9" viewBox="0 0 9 9" fill="none">
										  <path d="M0.969231 9L0 8.03077L6.64615 1.38462H0.692308V0H9V8.30769H7.61538V2.35385L0.969231 9Z" fill="currentColor"></path>
										</svg>
									</a>
								</div>
								
								
                               
                            </div>
                        </div>
                        <?php if (($count % $nb_rows == 0 || $count == $count_item)) { ?>
                        </div>
                    <?php } ?>
                    <?php endforeach; ?>
                </div>

                <div class="loading-content"><span class="hidden"><?php echo __('Loading...') ?></span></div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            ;(function (el) {
                var $element = $(el);

                function _countDown(date, id) {
                    var dateNow = new Date();
                    var amount = date.getTime() - dateNow.getTime();
                    delete dateNow;
                    if (amount < 0) {
                        id.html("Now!");
                    } else {
                        var days = 0;
                        hours = 0;
                        mins = 0;
                        secs = 0;
                        out = "";
                        amount = Math.floor(amount / 1000);
                        days = Math.floor(amount / 86400);
                        amount = amount % 86400;
                        hours = Math.floor(amount / 3600);
                        amount = amount % 3600;
                        mins = Math.floor(amount / 60);
                        amount = amount % 60;
                        secs = Math.floor(amount);
                        $(".time-day .num-time", id).text(days);
                        $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day') ?>" : "<?php echo __('Days') ?>"));
                        $(".time-hours .num-time", id).text(hours);
                        $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour') ?>" : "<?php echo __('Hours') ?>"));
                        $(".time-mins .num-time", id).text(mins);
                        $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min') ?>" : "<?php echo __('Mins') ?>"));
                        $(".time-secs .num-time", id).text(secs);
                        $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec') ?>" : "<?php echo __('Secs') ?>"));
                        setTimeout(function () {
                            _countDown(date, id)
                        }, 1000);
                    }
                }

                $(".deals-countdown", $element).each(function () {
                    var timer = $(this).data('timer');
                    var data = new Date(timer);
                    _countDown(data, $(this));
                });
            })('#<?php echo $tag_id ?>');
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
