<?php
$_config = $this->helper('Sm\Themecore\Helper\Data'); 
?> 
<div class="header-top">
	    <div class="container">
		    <div class="row align-items-center">
		        <div class="col-lg-4 d-none d-lg-block"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-7-toplinks')->toHtml(); ?></div>
		        <div class="col-lg-4"> 
					<div class="hdt-text-center slider-header-text"> 
					<?php  echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('slider-header-text')->toHtml(); ?> 
					</div>
				</div>
		        <div class="col-lg-4 d-none d-lg-block"> 
		          	<div class="right-header-top hdt-align-center">
		          		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-7-contact')->toHtml(); ?>
		          	</div>
		        </div>
		    </div>
	    </div>
	</div>
<div class="header-container header-style-10">

	    <div class="container">
		    <div class="row header-content">
		      	<div class="col-lg-4">
		        	<div class="logo-container"> <?php echo $this->getChildHtml("logo"); ?> </div>
		        </div>
		        <div class="col-lg-4">
		        	<div class="search-container search-header">
			           <div class="popup-search">
			            	<div class="box-search" data-move="search-mobile"> 
								<?php echo $this->getChildHtml("topSearch"); ?>
							</div>
						</div>
		          	</div>
		        </div>
		        <div class="col-lg-4">
		        	<div class="customer-actions hdt-justify-end">          	
			          	<div class="customer-links" data-move="customer-mobile">
			          		<?php echo $this->getChildHtml("header.links"); ?>          		
			          	</div>
			          	<ul class="header-compare">
							<li><a href=" <?php echo $this->getUrl('catalog/product_compare/index/');?> " title="<?php echo __('Compare');?>"><?php echo __('Compare');?></a></li>
						</ul> 
			          	<?php echo $this->getChildHtml("wishlist.header"); ?>
			          	<div class="minicart-header" data-move="minicart-mobile"><?php echo $this->getChildHtml("minicart"); ?></div>
			        </div>
			    </div>
			</div>
		</div>
        
		<div class="header-bottom ontop-element">
			<div class="container hdt-flex hdt-align-center hdt-justify-start">
		    	<!--div class="vertical-block"><?php //echo $this->getChildHtml("vertical-css"); ?></div-->
		    	<div class="vertical-block">
					<div class="vertical-menu-block">
						<div class="block-title-menu"><?php echo __('All Categories');?></div> 
						<div class="vertical-menu-content">
							<?php 
								echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menu-shop-mobile')->toHtml(); 
							?>
						</div>
					</div>	
				</div>
		    	<div class="horizontal-block"><?php
						if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
							echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
						} else {
							echo $this->getChildHtml("horizontal-css");
						}
					?> 
				</div>
				<div class="header-hotline">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-7-hotline')->toHtml(); ?>
				</div>		
		    </div>
		</div>



</div>