<?php
$_config = $this->helper('Sm\Themecore\Helper\Data'); 
?>
<div class="header-top">
		<div class="topbar-close">
			<button class="btn-close">
				<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12" fill="currentColor">
					<path d="M12 1.20857L10.7914 0L6 4.79143L1.20857 0L0 1.20857L4.79143 6L0 10.7914L1.20857 12L6 7.20857L10.7914 12L12 10.7914L7.20857 6L12 1.20857Z" fill="currentColor"></path>
				</svg>
			</button>
		</div>		
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header4-marquee')->toHtml(); ?>		
	</div>
<div class="header-container header-style-4">
		<div class="main-header">
			<div class="container">
				<div class="header-content clearfix">
					<div class="header-content-left"></div>	
				
					<div class="logo-container">
						<?php echo $this->getChildHtml("logo"); ?>
					</div>				

					<div class="customer-actions">
						
						<div class="search-container search-header">
							<a href="javascript:void(0)" class="btn-search icon-search1"><span class="hidden"></span></a>
							<div class="popup-search">
								<div class="box-search" data-move="search-mobile"> 
									<?php echo $this->getChildHtml("topSearch"); ?>
								</div>
								<a class="close-search" href="javascript:void(0);">
											<span class="hidden"><?php echo __('Close') ?></span>
								</a>
								<?php 
									echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product-search')->toHtml();
								?>
							</div>
							
						</div>
						<div class="customer-links" data-move="customer-mobile">
							<?php echo $this->getChildHtml("header.links"); ?>

						</div>
						<?php echo $this->getChildHtml("wishlist.header"); ?>
						<div class="minicart-header" data-move="minicart-mobile">
						<?php echo $this->getChildHtml("minicart"); ?>
						</div>						
					</div>
				</div>							
			</div>	
		</div>
		
		<div class="header-bottom ontop-element">
			<div class="container">
				<div class="horizontal-block">
				<?php
					if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
						echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
					} else {
						echo $this->getChildHtml("horizontal-css");
					}
				?>
				</div>
			</div>
		</div>
	
</div>
