<?php
$_config = $this->helper('Sm\Themecore\Helper\Data'); 
?>
<div class="header-container ontop-element header-style-1">
		<div class="container">
			<div class="header-content clearfix">
				<?php // echo $this->getChildHtml("nav.mobile"); ?>		
				<div class="logo-container">
					<?php echo $this->getChildHtml("logo"); ?>
				</div>
				<div class="horizontal-block">
				<?php
					if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
						echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
					} else {
						echo $this->getChildHtml("horizontal-css");
					}

				?>
				</div>
				
				<div class="customer-actions">
					<div class="search-container search-header">
						<a href="javascript:void(0)" class="btn-search icon-search1"><span class="hidden"></span></a>
						<div class="popup-search">
							<div class="box-search" data-move="search-mobile"> 
								<?php echo $this->getChildHtml("topSearch"); ?>
							</div>
							<a class="close-search" href="javascript:void(0);">
                                        <span class="hidden"><?php echo __('Close') ?></span>
                            </a>
							<?php 
								echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product-search')->toHtml();
							?>
						</div>
						
					</div>
					<div class="customer-links" data-move="customer-mobile">
						<?php echo $this->getChildHtml("header.links"); ?>
					</div>
					<?php echo $this->getChildHtml("wishlist.header"); ?>
					<div class="minicart-header" data-move="minicart-mobile">
					<?php  echo $this->getChildHtml("minicart"); ?> 
					</div>
					
				
				</div>
			</div>
		</div>


</div>
