<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$_postCollection   = $block->getPostCollection();
$_config           = $this->helper('Sm\Themecore\Helper\Data');
$enableLadyLoading = $_config->getAdvanced('lazyload_group/enable_ladyloading');
$mediaSrc          = $_config->getMediaUrl();
if ($enableLadyLoading) {
    $imgClass = 'lazyload';
} else {
    $imgClass = '';
}
?>
<div class="block block-slider-post">
    <div class="block-title">
        <strong><?php echo $block->escapeHtml($block->getTitle()) ?></strong>
    </div>

    <div class="block-content">
        <?php if ($_postCollection->count()) { ?>
            <div class="owl-carousel owl-theme">
                <?php foreach ($_postCollection as $_post) { ?>
                    <?php
                    $_postUrl  = $_post->getPostUrl();
                    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                    ?>
                    <div class="item">
                        <div class="image-post">
                            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                    <img class="<?php echo $imgClass; ?>"
                                        <?php if ($enableLadyLoading) { ?>
                                            src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                            data-src="<?php echo $featuredImage ?>"
                                            width="1" height="1"
                                        <?php } else { ?>
                                            src="<?php echo $featuredImage ?>"
                                        <?php } ?>
                                         alt="<?php echo $_postName ?>"/>
                                </a>
                            <?php } else { ?>
                                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                    <img src="<?php /* @escapeNotVerified */
                                    echo $block->getViewFileUrl('images/post/no_image.jpg') ?>"
                                         alt="<?php echo $_postName ?>"/>
                                </a>
                            <?php } ?>
                            <div class="post-date">
                                <span><?php echo $_post->getPublishDate('F d, Y') ?></span>
                            </div>
                        </div>

                        <div class="info-post">
                            <div class="post-title">
                                <a class="post-item-link"
                                   href="<?php echo $_postUrl ?>">
                                    <?php echo $_postName; ?>
                                </a>
                            </div>
                            <div class="post-short-description">
                                <?php echo strip_tags($block->getShorContent($_post)) ?>
                            </div>                            
                            <a class="read-more"
                               href="<?php echo $_postUrl ?>">
                                <?php echo __('Read more'); ?>
                                <svg xmlns="http://www.w3.org/2000/svg" width="8" height="8" viewBox="0 0 8 8" fill="none" class="hdt-inline-block hdt-icon hdt-icon-2">
                                  <path d="M0.861539 8L0 7.13846L5.90769 1.23077H0.615385V0H8V7.38462H6.76923V2.09231L0.861539 8Z" fill="currentColor"></path>
                                </svg>
                            </a>
                            
                        </div>
                    </div>
                <?php } ?>
            </div>

            <div class="loading-content">
                <span class="hidden"><?php echo __('Loading...') ?></span>
            </div>
        <?php } else { ?>
            <div class="message info empty">
                <div><?php /* @escapeNotVerified */
                    echo __('We can\'t find post matching the selection.') ?></div>
            </div>
        <?php } ?>
    </div>
</div>
